import = ["~/.dotfiles/config/alacritty/themes/gruvbox-material-dark-hard.toml"]
live_config_reload = true
working_directory = "None"

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"
style = { shape = "Beam" }

[font]
size = 13
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
offset = { x = 1, y = 0 }

[scrolling]
history = 100000

[shell]
args = ["--login"]
program = "/usr/local/bin/fish"

[window]
dynamic_title = true
option_as_alt = "Both"
