---
- defaults:
    links:
      create: true
      relink: true

- clean: ['~', '~/.config']

- create:
  - ~/.bin
  - ~/.config
  - ~/.local/config

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [./environments/conda/bootstrap-conda.sh]
  - [./environments/rust/bootstrap-rust.sh]
  - [./tools/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc: shells/bash/bashrc

    # Readline
    ~/.inputrc: shells/readline/inputrc

    # ZSH
    ~/.zshrc: shells/zsh/zshrc_5_0
    ~/.zshenv: shells/zsh/zshenv
    
    # Scripts
    ~/.bin:
      path: shells/bin/*
      glob: true
      exclude:
        - bin/README.md
    
    # Tmux
    ~/.tmux.conf:
      path: tools/tmux/tmux_1_9.conf

    # Vim
    ~/.vimrc: tools/vim/light.vim

    # NeoVim
    ~/.config/nvim/init.vim: 
        path: tools/vim/full.vim
        create: true

    # Git
    ~/.gitconfig: tools/git/gitconfig

    # Screen
    ~/.screenrc:
      path: tools/screen/screenrc
    
    # Dir colors
    ~/.dir_colors: shells/dircolors/dir_colors.gruvbox

    # Conda
    ~/.condarc: environments/conda/condarc

