---
- defaults:
    links:
      create: true
      relink: true

- clean: ['~', '~/.config']

- create:
  - ~/.bin
  - ~/.config

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [./conda/bootstrap.sh]
  - [./fzf/bootstrap.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc: bash/bashrc

    # Readline
    ~/.inputrc: readline/inputrc

    # ZSH
    ~/.zshrc:
      if: 'command -v zsh &>/dev/null'
      path: zsh/zshrc_5_0
      force: true
    
    # Scripts
    ~/.bin:
      path: bin/*
      glob: true
      exclude:
        - bin/README.md
    
    # Tmux
    ~/.tmux.conf:
      if: 'command -v tmux &>/dev/null'
      path: tmux/tmux_1_9.conf

    # Vim
    ~/.vimrc:
      if: 'command -v vim &>/dev/null || command -v vi &>/dev/null'
      path: vim/light.vim

    # Git
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global

    # Screen
    ~/.screenrc:
      if: 'command -v screen &>/dev/null'
      path: screen/screenrc
    
    # Dir colors
    ~/.dir_colors: dircolors/dir_colors

    # Conda
    ~/.condarc: conda/condarc

