---
- defaults:
    links:
      create: true
      relink: true

- clean: 
    - '~'
    - '~/.config'

- create:
  - ~/.bin
  - ~/.config
  - ~/.local/config

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [./config/conda/bootstrap-conda.sh]
  - [./config/rust/bootstrap-rust.sh]
  - [./config/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc: config/bash/bashrc

    # Readline
    ~/.inputrc: config/readline/inputrc

    # ZSH
    ~/.zshrc: config/zsh/zshrc_5_0
    ~/.zshenv: config/zsh/zshenv
    
    # Scripts
    ~/.bin:
      path: config/bin/*
      glob: true
      exclude:
        - bin/README.md
    
    # Tmux
    ~/.tmux.conf:
      path: config/tmux/tmux_1_9.conf

    # Vim
    ~/.vimrc: config/vim/light.vim

    # NeoVim
    ~/.config/nvim/init.vim: 
        path: config/vim/full.vim
        create: true

    # Git
    ~/.gitconfig: config/git/gitconfig

    # Screen
    ~/.screenrc:
      path: config/screen/screenrc
    
    # Dir colors
    ~/.dir_colors: config/dircolors/dir_colors.gruvbox

    # Conda
    ~/.condarc: config/conda/condarc

