---
- defaults:
    links:
      create: true
      relink: true

- clean: 
  - '~'
  - '~/.config'

- create:
  - ~/.bin
  - ~/.config
  - ~/.local/config
  - ~/workspace

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [./config/conda/bootstrap-conda.sh]
  - [./config/rust/bootstrap-rust.sh]
  - [./config/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc: config/bash/bashrc

    # Readline
    ~/.inputrc: config/readline/inputrc

    # ZSH
    ~/.zshrc:
      if: 'command -v zsh &>/dev/null'
      path: config/zsh/zshrc
      force: true

    ~/.zshenv:
      if: 'command -v zsh &>/dev/null'
      path: config/zsh/zshenv
      force: true
      
    # Fish
    ~/.config/fish:
      if: 'command -v fish &>/dev/null'
      path: config/fish

    ~/.config/nushell:
      if: 'command -v nu &>/dev/null && [[ $(uname) = Linux ]]'
      path: config/nushell

    ~/Library/Application Support/nushell:
      if: 'command -v nu &>/dev/null && [[ $(uname) = Darwin ]]'
      path: config/nushell
    
    # Starship prompt
    ~/.config/starship.toml:
      path: config/starship/starship.toml

    # FD ignore file.
    ~/.config/fd:
      path: config/fd
    
    # Tmux
    ~/.tmux.conf:
      if: 'command -v tmux /dev/null'
      path: config/tmux/tmux_full.conf

    # Vim
    ~/.vimrc:
      path: config/vim/light.vim

    # Neovim
    ~/.config/nvim:
      if: 'command -v nvim &/dev/null'
      path: config/nvim

    # Git
    ~/.gitconfig: config/git/gitconfig

    # Screen
    ~/.screenrc:
      if: 'command -v screen &>/dev/null'
      path: config/screen/screenrc
    
    # Dir colors
    ~/.dir_colors: config/dircolors/dir_colors.gruvbox

    # Conda
    ~/.condarc:
      if: 'command -v conda &>/dev/null'
      path: config/conda/condarc

    # Alacritty
    ~/.config/alacritty/alacritty.yml:
      if: 'command -v alacritty &>/dev/null'

      path: config/alacritty/alacritty-arch.yaml

      # Path for MacOS
      # path: config/alacritty/alacritty-mac.yaml

      create: true

    # WezTerm
    ~/.config/wezterm:
      if: 'command -v wezterm &>/dev/null'
      path: config/wezterm
      create: true

    # Jetbrains vim emulator
    ~/.ideavimrc: config/jetbrains/ideavimrc

    # VSCode Linux
    ~/.config/Code/User:
      if: '[[ $(uname) = Linux ]]'
      glob: true
      path: config/vscode/linux/*.json
      force: true
      create: true
    
    # VSCode MacOS
    ~/Library/Application Support/Code/User:
      if: '[[ $(uname) = Darwin ]]'
      glob: true
      path: config/vscode/macos/*.json
      force: true
      create: true

