---
- defaults:
    links:
      create: true
      relink: true

- clean: ['~', '~/.config']

- create:
  - ~/.bin
  - ~/.config
  - ~/Workspace

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [./environments/conda/bootstrap-conda.sh]
  - [./environments/rust/bootstrap-rust.sh]
  - [./tools/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc: shells/bash/bashrc

    # Readline
    ~/.inputrc: shells/readline/inputrc

    # ZSH
    ~/.zshrc:
      if: 'command -v zsh &>/dev/null'
      path: shells/zsh/zshrc
      force: true

    ~/.zshenv:
      if: 'command -v zsh &>/dev/null'
      path: shells/zsh/zshenv
      force: true
      
    # Fish
    ~/.config/fish/config.fish:
      if: 'command -v fish &>/dev/null'
      path: shells/fish/config.fish
      force: true
    
    ~/.config/fish/conf.d:
      if: 'command -v fish &>/dev/null'
      glob: true
      path: shells/fish/conf.d/*.fish
      force: true
      create: true

    ~/.config/fish/functions:
      if: 'command -v fish &>/dev/null'
      glob: true
      path: shells/fish/functions/*.fish
      create: true

    # Starship prompt
    ~/.config/starship.toml:
      path: shells/starship/starship.toml
      force: true
    
    # Scripts
    ~/.bin:
      path: shells/bin/*
      glob: true
      exclude:
        - bin/README.md
    
    # Tmux
    ~/.tmux.conf:
      path: tools/tmux/tmux_full.conf

    # Vim
    ~/.vimrc:
      path: tools/vim/light.vim

    # Neovim
    ~/.config/nvim:
      path: tools/nvim
      create: true
    # Git
    ~/.gitconfig: tools/git/gitconfig
    ~/.gitignore_global: tools/git/gitignore_global

    # Screen
    ~/.screenrc:
      path: tools/screen/screenrc
    
    # Dir colors
    ~/.dir_colors: shells/dircolors/dir_colors.gruvbox

    # Conda
    ~/.condarc: environments/conda/condarc

    # Alacritty
    ~/.config/alacritty/config:
      path: emulators/alacritty/alacritty.yml
      create: true

    # Jetbrains vim emulator
    ~/.ideavimrc: ides/jetbrains/ideavimrc

    # VSCode Linux
    ~/.config/Code/User:
      if: '[[ $(uname) = Linux ]]'
      glob: true
      path: ides/vscode/linux/*.json
      force: true
      create: true
    
    # VSCode MacOS
    ~/Library/Application Support/Code/User:
      if: '[[ $(uname) = Darwin ]]'
      glob: true
      path: ides/vscode/macos/*.json
      force: true
      create: true

