- defaults:
    link:
      create: true
      relink: true

- clean:
    - '~'
    - '~/.config'

- create:
    - ~/.bin
    - ~/.config
    - ~/.local/config
    - ~/workspace

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [./config/conda/bootstrap-conda.sh]
    - [./config/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc: config/bash/bashrc

    # Readline
    ~/.inputrc: config/readline/inputrc

    # ZSH
    ~/.zshrc:
      path: config/zsh/zshrc
      force: true
    ~/.zshenv:
      if: 'command -v zsh &>/dev/null'
      path: config/zsh/zshenv
      force: true

    # Tmux
    ~/.tmux.conf: config/tmux/tmux_minimal.conf

    # Vim
    ~/.vimrc: config/vim/light.vim

    # Git
    ~/.gitconfig: config/git/gitconfig

    # Screen
    ~/.screenrc: config/screen/screenrc

    # Dir colors
    ~/.dir_colors: dircolors/dir_colors
