
---
- defaults:
    link:
      create: true
      relink: true

- clean: ['~']

- create:
  - ~/.bin
  - ~/.config
  - ~/workspace

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - [./environments/conda/bootstrap-conda.sh]
  - [./tools/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc: shells/bash/bashrc

    # Readline
    ~/.inputrc: shells/readline/inputrc

    # ZSH
    ~/.zshrc:
      path: shells/zsh/zshrc
      force: true
    ~/.zshenv:
      if: 'command -v zsh &>/dev/null'
      path: shells/zsh/zshenv
      force: true

    # Tmux
    ~/.tmux.conf: tmux/tmux_minimal.conf

    # Vim
    ~/.vimrc: tools/vim/light.vim

    # Git
    ~/.gitconfig: tools/git/gitconfig
    ~/.gitignore_global: tools/git/gitignore_global

    # Screen
    ~/.screenrc: tools/screen/screenrc
    
    # Dir colors
    ~/.dir_colors: dircolors/dir_colors
