---
- defaults:
    links:
      create: true
      relink: true

- clean: 
  - '~'
  - '~/.config'

- create:
  - ~/.bin
  - ~/.config
  - ~/.local/config

- shell:
  - ['git submodule update --init --recursive', 'Installing submodules']
  - [./config/conda/bootstrap-conda.sh]
  - [./config/rust/bootstrap-rust.sh]
  - [./config/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc:
      path: config/bash/bashrc
      force: true

    # Readline
    ~/.inputrc:
      path: config/readline/inputrc
      force: true

    # ZSH
    ~/.zshrc:
      if: 'command -v zsh &>/dev/null'
      path: config/zsh/zshrc
      force: true

    ~/.zshenv:
      if: 'command -v zsh &>/dev/null'
      path: config/zsh/zshenv
      force: true

    # Tmux
    ~/.tmux.conf:
      if: 'command -v tmux &>/dev/null'
      path: config/tmux/tmux_full.conf

    # Vim
    ~/.vimrc: config/vim/light.vim

    # Neovim
    ~/.config/nvim/init.vim:
      if: 'command -v nvim &>/dev/null'
      path: config/vim/full.vim
      force: true

    # FD ignore file.
    ~/.config/fd:
      path: config/fd
    
    # Git
    ~/.gitconfig: config/git/gitconfig

    # Screen
    ~/.screenrc:
      if: 'command -v screen &>/dev/null'
      path: config/screen/screenrc
    
    # Dir colors
    ~/.dir_colors: config/dircolors/dir_colors.gruvbox

    # Conda
    ~/.condarc:
      if: 'command -v conda &>/dev/null'
      path: config/conda/condarc

