---
- defaults:
    links:
      create: true
      relink: true

- clean: ['~', '~/.config']

- create:
  - ~/.bin
  - ~/.config
  - ~/.local/config

- shell:
  - ['git submodule update --init --recursive', 'Installing submodules']
  - [./environments/conda/bootstrap-conda.sh]
  - [./environments/rust/bootstrap-rust.sh]
  - [./tools/fzf/bootstrap-fzf.sh]

- link:
    ~/.dotfiles:
      if: '[[ ! -d ~/.dotfiles ]]'
      path: ""

    # Bash
    ~/.bashrc:
      path: shells/bash/bashrc
      force: true

    # Readline
    ~/.inputrc:
      path: shells/readline/inputrc
      force: true

    # ZSH
    ~/.zshrc:
      if: 'command -v zsh &>/dev/null'
      path: shells/zsh/zshrc
      force: true

    ~/.zshenv:
      if: 'command -v zsh &>/dev/null'
      path: shells/zsh/zshenv
      force: true

    # Tmux
    ~/.tmux.conf:
      if: 'command -v tmux &>/dev/null'
      path: tools/tmux/tmux_full.conf

    # Vim
    ~/.vimrc: tools/vim/light.vim

    # Neovim
    ~/.config/nvim/init.vim:
      if: 'command -v nvim &>/dev/null'
      path: tools/vim/full.vim
      force: true

    # FD ignore file.
    ~/.config/fd:
      path: tools/fd
    
    # Git
    ~/.gitconfig: tools/git/gitconfig

    # Screen
    ~/.screenrc:
      if: 'command -v screen &>/dev/null'
      path: tools/screen/screenrc
    
    # Dir colors
    ~/.dir_colors: shells/dircolors/dir_colors.gruvbox

    # Conda
    ~/.condarc:
      if: 'command -v conda &>/dev/null'
      path: environments/conda/condarc

