[colors.bright]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xeee0b7"
yellow = "0xb47109"

[colors.normal]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xeee0b7"
yellow = "0xb47109"

[colors.primary]
background = "0xfbf1c7"
foreground = "0x654735"
