# ----------------
# |   Dotfiles   |
# ----------------
DOTFILES: ${HOME}/.dotfiles
DOTFILES_BIN: ${HOME}/.dotfiles/bin
LOCAL_CONFIG: ${HOME}/.local/config

# ---------------
# |   General   |
# ---------------
EDITOR: nvim
VISUAL: nvim

# -----------
# |   Man   |
# -----------
MANPAGER: nvim +Man!

# ---------------
# |   Neovide   |
# ---------------
NEOVIDE_MULTIGRID: true

# -----------
# |   Bat   |
# -----------
BAT_THEME: gruvbox-dark

# --------------------
# |   GNU Parallel   |
# --------------------
PARALLEL_HOME: ${HOME}/.local/share/parallel

# --------------
# |   Golang   |
# --------------
GOPATH: ${HOME}/.local/share/go

# -----------
# |   FZF   |
# -----------
FZF_DEFAULT_COMMAND:
  - if:
      cmd: fd
    then: 'fd --type file --follow --hidden --exclude .git --color=always'
  - if:
      cmd: rg
    then: 'rg --files --no-ignore --hidden --follow --glob "!.git/*"'

FZF_CTRL_T_COMMAND:
  - if:
      cmd: fd
    then: $FZF_DEFAULT_COMMAND
FZF_DEFAULT_OPTS: '--ansi --bind ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-/:toggle-preview,ctrl-t:toggle-preview-wrap --cycle --reverse --border rounded --height 50% --min-height 20 --preview-window right,40%'
