# ----------------
# |   Dotfiles   |
# ----------------
#
# Dotfiles installation dir.
DOTFILES: ${HOME}/.dotfiles

# Bin directory for scripts.
DOTFILES_BIN: ${HOME}/.dotfiles/bin

# Local configuration files that extend the managed configs.
DOTFILES_LOCAL: ${HOME}/.local/config

# ---------------
# |   General   |
# ---------------
EDITOR: nvim
VISUAL: nvim

# -----------
# |   Bat   |
# -----------
BAT_THEME: gruvbox-dark

# -------------
# |   Cargo   |
# -------------
CARGO_HOME: ${HOME}/.local/share/cargo

# -----------
# |   FZF   |
# -----------
FZF_DEFAULT_COMMAND:
  - if:
      cmd: fd
    then: 'fd --type file --follow --hidden --exclude .git --color=always'
  - if:
      cmd: rg
    then: 'rg --files --no-ignore --hidden --follow --glob "!.git/*"'

FZF_CTRL_T_COMMAND:
  - if:
      cmd: fd
    then: $FZF_DEFAULT_COMMAND

FZF_DEFAULT_OPTS: >
  --ansi --cycle --reverse --border rounded
  --height 50% --min-height 20 --preview-window right,40%
  --bind ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up
  --bind ctrl-d:half-page-down,ctrl-u:half-page-up
  --bind ctrl-/:toggle-preview,ctrl-t:toggle-preview-wrap

# --------------------
# |   GNU Parallel   |
# --------------------
PARALLEL_HOME: ${HOME}/.local/share/parallel

# --------------
# |   Golang   |
# --------------
GOPATH: ${HOME}/.local/share/go

# -----------
# |   Man   |
# -----------
MANPAGER: nvim +Man!

# ---------------
# |   Neovide   |
# ---------------
NEOVIDE_MULTIGRID: true

# --------------
# |   Rustup   |
# --------------
RUSTUP_HOME: ${HOME}/.local/share/rustup
