#!/usr/bin/env bash

case $DOTBOT_OS in
  Darwin) target=~/Library/Application Support/Code/User ;;
  */Linux) target=~/.config/code/user ;;
  *) exit 129 ;;
esac

if [[ ! -f $target || $DOTBOT_FORCE == yes ]]; then
  mkdir "$(dirname "$target")"
  cp "$PWD/settings.json" "$target"
fi
