#!/usr/bin/env bash

command -v nu &>/dev/null || exit 128

case $DOTBOT_OS in
  Darwin) target=~/Library/Application\ Support/nushell ;;
  */Linux) target=~/.config/nushell ;;
  *) exit 129 ;;
esac

symlinkfb "$PWD" "$target"
