#!/usr/bin/env bash

hascommand nu || exit 128

case $DOTBOT_OS_SHORT in
  darwin) target=~/Library/Application\ Support/nushell ;;
  linux) target=~/.config/nushell ;;
  *) exit 129 ;;
esac

symlinkfb "$PWD/config.nu" "$target/config.nu"
symlinkfb "$PWD/env.nu" "$target/env.nu"
