#!/usr/bin/env bash

command -v nu &>/dev/null || exit 1

case $DOTFILES_OS in
  Darwin) target=~/Library/Application\ Support/nushell ;;
  Linux) target=~/.config/nushell ;;
esac

symlinkfb "$PWD" "$target"
