#!/usr/bin/env bash

cleanlinks \
  ~ \
  ~/.config \
  ~/.local/config

mkdir -p \
  ~/.config \
  ~/.local/{bin,config} \
  ~/workspace/{lib,playground,repos,tools}

[[ -d ~/.dotfiles ]] || symlinkfb "$PWD" ~/.dotfiles
