#!/usr/bin/env bash

export DOTFILES_HOME=$PWD
DOTFILES_OS=$(uname -o)
export DOTFILES_OS

bash dotbot

for config_dotbot in config/*/dotbot; do
  pushd "$(dirname "$config_dotbot")" || exit

  bash "$config_dotbot"

  popd || exit
done
