#!/bin/zsh

alias zshconfig="${EDITOR} ~/.zshrc"
alias gitconfig="${EDITOR} ~/.gitconfig"

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

if command -v exa &>/dev/null; then
  alias l='exa'
  alias ls='exa'
  alias lg='exa --git'
  alias ll='exa -l'
  alias lt='exa --tree'
  alias lll='exa -la'
else
  alias l='ls'
  alias ll='ls -l'
  alias lll='ls -lA'
fi

if command -v hyperfine &>/dev/null; then
  alias hf='hyperfine'
fi

alias grep='grep -i --color=auto'
alias tmux='TERM=xterm-256color tmux'

