#!/usr/bin/env bash

#######################################################################
#                               Exports                               #
#######################################################################
# Set the dotfiles config
export DOTFILES="${HOME}/.dotfiles"
export DOTFILES_BASH="${DOTFILES}/config/bash"
export DOTFILES_SH="${DOTFILES}/config/sh"
export LOCAL_CONFIG="${HOME}/.local/config"
export PATH="${HOME}/.bin:${DOTFILES}/bin:${HOME}/.local/bin:/usr/local/bin:/opt/vc/bin:${PATH}"

export MY_SHELL="bash"
export LC_ALL=en_US.UTF-8

### Editor ###
if command -v nvim &>/dev/null; then
  export VISUAL="nvim"
else
  export VISUAL="vim"
fi
export EDITOR="${VISUAL}"

### Go ###
export GOPATH="${HOME}/.local/share/go"

### FZF ###
if command -v fd &>/dev/null; then
  export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git --color=always'
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
  export FZF_DEFAULT_OPTS='--ansi'
elif command -v rg &>/dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
fi
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --bind ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up,ctrl-d:half-page-down,ctrl-u:half-page-up,ctrl-/:toggle-preview --border --height 50% --min-height 20 --preview-window right,40%,follow"


#######################################################################
#                               History                               #
#######################################################################
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=100000
export HISTIGNORE="ls:ll:cd:cd -:pwd:exit:date:* --help"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


#######################################################################
#                        Prompt Customization                         #
#######################################################################
# Set editing mode to Vi mode
set editing-mode vi
set -o vi

# Reset cursor
export PS0="\e[5 q"

# Load the custom prompt
source "${DOTFILES_BASH}/ps1rc"
PS1="$(__mkps1)"

# Enable programmable completion features
if ! shopt -oq posix; then
  if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    . /usr/share/bash-completion/bash_completion
  elif [[ -f /etc/bash_completion ]]; then
    . /etc/bash_completion
  fi
fi

# Paste the arguments from the last command
bind -m vi-command '"p": "i !!*\r"'

# Add a pipe
bind -m vi-command '"P": "A | "'
bind -m vi-insert '"\C-x\C-p": "\e-A | "'

# Pipe to less
bind -m vi-insert '"\C-x\C-l": "\e-A | less\r"'

# Insert the arguments from the last command
bind -m vi-command '"o": "0Eli "'
bind -m vi-insert '"\C-o": "\e-0Eli "'

source "${DOTFILES_SH}/functions/fzf-git.sh"
if [[ $- =~ i ]]; then
  bind '"\er": redraw-current-line'
  bind '"\C-g\C-f": "$(_gf)\e\C-e\er"'
  bind '"\C-g\C-b": "$(_gb)\e\C-e\er"'
  bind '"\C-g\C-t": "$(_gt)\e\C-e\er"'
  bind '"\C-g\C-h": "$(_gh)\e\C-e\er"'
  bind '"\C-g\C-r": "$(_gr)\e\C-e\er"'
  bind '"\C-g\C-s": "$(_gs)\e\C-e\er"'
fi


#######################################################################
#                               Aliases                               #
#######################################################################

# Source fzf and cargo
if [[ -f "${HOME}/.fzf.bash" ]]; then
  source "${HOME}/.fzf.bash"
elif [[ -f /usr/share/fzf/key-bindings.bash ]]; then
  source /usr/share/fzf/key-bindings.bash
fi

[[ -f "${HOME}/.cargo/env" ]] && source "${HOME}/.cargo/env"

# Load user aliases
[[ -f "${DOTFILES_BASH}/aliases" ]] && source "${DOTFILES_BASH}/aliases"
[[ -f "${DOTFILES_BASH}/git.aliases" ]] && source "${DOTFILES_BASH}/git.aliases"

# Load local aliases and configurations
[[ -f "${LOCAL_CONFIG}/aliases" ]] && source "${LOCAL_CONFIG}/aliases"
[[ -f "${LOCAL_CONFIG}/bashrc" ]] && source "${LOCAL_CONFIG}/bashrc"
