# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$kubernetes\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

[git_status]
ahead = " ${count}"
diverged = "󰓁 ( ${ahead_count} ${behind_count})"
behind = " ${count}"
conflicted = "=${count}"
untracked = "?${count}"
stashed = "${count}"
modified = "!${count}"
staged = "+${count}"
renamed = ">${count}"
deleted = "x${count}"

[hostname]
ssh_only = false
format = "@[$hostname]($style) "
disabled = false

[jobs]
disabled = false

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = true

[status]
disabled = false
symbol = ''

[time]
disabled = false

[username]
format = "[$user]($style)"
show_always = true
disabled = false
