language: ruby
dist: bionic
rvm:
- 2.6
install: gem install asciidoctor-pdf --pre
git:
  depth: 1
branches:
  only:
  - master
addons:
  apt:
    packages:
    - zsh
    - mailutils
env:
  global:
  - ENCRYPTION_LABEL: de1faff15945
  - COMMIT_AUTHOR_EMAIL: psprint@zdharma.org
before_script:
- sudo apt-get install -y zsh mailutils
- zsh --version
- 'zsh -c ''print -rl -- "ZSH_VERSION: $ZSH_VERSION" "ZSH_PATCHLEVEL: $ZSH_PATCHLEVEL"
  "OSTYPE: $OSTYPE" "CPUTYPE: $CPUTYPE" "MACHTYPE: $MACHTYPE"'''
script:
- git fetch --depth=1 origin tests:tests
- git worktree add test tests
- make
- make -C zsdoc pdf
- share/deploy_doc.sh
- make -C test test VERBOSE=1
- make -C test testB VERBOSE=1
- make -C test testC VERBOSE=1
- make -C test testD VERBOSE=1
- make -C test testE VERBOSE=1
notifications:
  irc:
    channels:
    - chat.freenode.net#zplugin
    on_success: change
    on_failure: change
    skip_join: true
  email:
    recipients:
      - sgniazdowski@gmail.com
    on_success: change
    on_failure: change
before_install:
- openssl aes-256-cbc -K $encrypted_52a7097f2175_key -iv $encrypted_52a7097f2175_iv
  -in share/deploy_key.enc -out share/deploy_key -d
