---@class LfsAttributes
---@field dev integer on Unix systems, this represents the device that the inode resides on. On Windows systems, represents the drive number of the disk containing the file
---@field ino string on Unix systems, this represents the inode number. On Windows systems this has no meaning
---@field mode string string representing the associated protection mode (the values could be file, directory, link, socket, named pipe, char device, block device or other)
---@field nlink integer number of hard links to the file
---@field uid integer user-id of owner (Unix only, always 0 on Windows)
---@field gid integer group-id of owner (Unix only, always 0 on Windows)
---@field rdev integer on Unix systems, represents the device type, for special file inodes. On Windows systems represents the same as dev
---@field access integer time of last access
---@field modification integer time of last data modification
---@field change integer time of last file status change
---@field size integer file size, in bytes
---@field permissions string file permissions string
---@field blocks integer block allocated for file; (Unix only)
---@field blksize integer optimal file system I/O blocksize; (Unix only)

---@class LfsSymlinkAttributes: LfsAttributes
---@field target string
