[font]
size = 11
normal = { family = "JetBrains Mono", style = "Regular" }

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal]
shell = {program = "/usr/bin/fish", args = ["--login"]}
