[font]
size = 13
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
offset = { x = 1, y = 0 }

[shell]
args = ["--login"]
program = "/usr/local/bin/fish"

[window]
option_as_alt = "Both"
