# Set the dotfiles directory
export DOTFILES="$HOME/.dotfiles"
export DOTFILES_ZSH="$DOTFILES/config/zsh"
export LOCAL_CONFIG="$HOME/.local/config/zsh"

export LC_ALL=en_US.UTF-8

# Modify the path
typeset -U path
path=(
  "$HOME/.local/bin"
  "$DOTFILES/bin/all"
  "$DOTFILES/bin/os/bin"
  /usr/local/bin
  $path
)

### Commands ###
## Bat ##
if command -v bat &>/dev/null; then
  export BAT_THEME="gruvbox-dark"
fi

## Editor ##
if command -v nvim &>/dev/null; then
  export VISUAL="nvim"
else
  export VISUAL="vim"
fi
export EDITOR="$VISUAL"

## FZF ##
if command -v fd &>/dev/null; then
  export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git --color=always'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
elif command -v rg &>/dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

export FZF_DEFAULT_OPTS="
  --ansi
  --bind ctrl-f:preview-half-page-down
  --bind ctrl-b:preview-half-page-up
  --bind ctrl-d:half-page-down
  --bind ctrl-u:half-page-up
  --bind ctrl-/:toggle-preview
  --bind ctrl-t:toggle-preview-wrap
  --cycle
  --reverse
  --border rounded
  --height 50%
  --min-height 20
  --preview-window right,40%"

## Cargo and Rust ##
[[ -f $HOME/.cargo/env ]] && source "$HOME/.cargo/env"

## Local Enviornment Config ##
[[ -f $LOCAL_CONFIG/zshenv ]] && source "$LOCAL_CONFIG/zshenv"
