# Set the dotfiles directory
export DOTFILES="$HOME/.dotfiles"
export DOTFILES_ZSH="$DOTFILES/config/zsh"
export LOCAL_CONFIG="$HOME/.local/config/zsh"

export LC_ALL=en_US.UTF-8

# Modify the path
typeset -U path
path=(
  "$HOME/.local/bin"
  "$DOTFILES/bin"
  /usr/local/bin
  $path
)

## Editor ##
export VISUAL="nvim"
export EDITOR="$VISUAL"

## Bat ##
export BAT_THEME="gruvbox-dark"

## FZF ##
export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git --color=always'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='
  --ansi
  --bind ctrl-f:preview-half-page-down
  --bind ctrl-b:preview-half-page-up
  --bind ctrl-d:half-page-down
  --bind ctrl-u:half-page-up
  --bind ctrl-/:toggle-preview
  --bind ctrl-t:toggle-preview-wrap
  --cycle
  --reverse
  --border rounded
  --height 50%
  --min-height 20
  --preview-window right,40%,follow'

## Homebrew ##
export HOMEBREW_NO_ENV_HINTS=1

## Local Environment Config ##
[[ -f $LOCAL_CONFIG/zshenv ]] && source "$LOCAL_CONFIG/zshenv"
