add_newline = true

# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$sudo\
$jobs\
$status\
$shell\
$character"""

right_format = """
$singularity\
$kubernetes\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$custom\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
"""

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
conflicted = "=${count}"
untracked = "?${count}"
stashed = "${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[hostname]
ssh_only = false
format = "@[$hostname]($style) "
disabled = false

[jobs]
disabled = false

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = true

[time]
disabled = false

[username]
format = "[$user]($style)"
show_always = true
disabled = false
