vim.opt_local.commentstring = "#%s"

-- vim.api.nvim_buf_create_user_command(0, "NuStart", function()
--   local buf_id = vim.api.nvim_get_current_buf()
--   local buf_name = vim.api.nvim_buf_get_name(buf_id)
--
--   local root_dir
--   if buf_name then
--     root_dir = vim.fs.dirname(buf_name)
--   end
--   if not root_dir then
--     root_dir = vim.uv.cwd()
--   end
--
--   local capabilities = require("cmp_nvim_lsp").default_capabilities(
--     vim.lsp.protocol.make_client_capabilities()
--   )
--
--   local client_id = vim.lsp.start_client({
--     name = "nu-lsp",
--     cmd = { "nu", "--lsp" },
--     root_dir = root_dir,
--     capabilities = capabilities,
--   })
--
--   if client_id then
--     vim.lsp.buf_attach_client(0, client_id)
--   else
--     vim.notify("failed to start nulsp", vim.log.levels.ERROR)
--   end
-- end, {})
