vim.keymap.set("n", "dd", function()
  local entry = vim.fn.line(".")
  local qflist = vim.fn.getqflist()
  table.remove(qflist, entry)
  vim.fn.setqflist(qflist)
  vim.cmd(entry .. "cfirst")
  vim.cmd.copen()
end, { buffer = true, desc = "Remove an entry from the quickfix list" })
